# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{skinnycms_tumblr}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["RuslanHamidullin"]
  s.date = %q{2011-02-25}
  s.description = %q{long description}
  s.email = %q{ruslan.hamidullin@flatsoft.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/admin/posts_controller.rb",
    "app/models/cache_tumblr_post.rb",
    "config/routes.rb",
    "config/shedule.rb",
    "init.rb",
    "lib/generators/skinnycms_tumblr/USAGE",
    "lib/generators/skinnycms_tumblr/skinnycms_tumblr_generator.rb",
    "lib/generators/skinnycms_tumblr_migrations/USAGE",
    "lib/generators/skinnycms_tumblr_migrations/migrations/add_skinnycms_fields_to_cache_tumblr_posts.rb",
    "lib/generators/skinnycms_tumblr_migrations/migrations/create_cache_tumblr_posts.rb",
    "lib/generators/skinnycms_tumblr_migrations/skinnycms_tumblr_migrations_generator.rb",
    "lib/skinnycms_tumblr.rb",
    "lib/skinnycms_tumblr/engine.rb",
    "lib/skinnycms_tumblr/railties/tasks.rake",
    "skinnycms_tumblr.gemspec"
  ]
  s.homepage = %q{https://github.com/fiftyandfifty/skinnycms_tumblr}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Lightweight CMS which leverages the lastest external social networking APIs}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.3"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.1"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.3"])
      s.add_dependency(%q<jeweler>, ["= 1.5.1"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.3"])
    s.add_dependency(%q<jeweler>, ["= 1.5.1"])
  end
end

